import crypto from 'node:crypto';
import { env } from '../config/env.js';

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 16;
const SALT_LENGTH = 64;

/**
 * Encrypts a plain text string using AES-256-GCM.
 * The output format is: v1:iv:salt:tag:ciphertext (all hex encoded)
 */
export function encrypt(text: string): string {
  if (!text) return text;
  
  // Ensure we have a valid secret key
  if (!env.API_SECRET || env.API_SECRET.length < 32) {
    throw new Error('API_SECRET must be at least 32 characters long to use encryption');
  }

  // Generate random initialization vector and salt
  const iv = crypto.randomBytes(IV_LENGTH);
  const salt = crypto.randomBytes(SALT_LENGTH);

  // Derive a strong key from the secret and salt
  const key = crypto.pbkdf2Sync(env.API_SECRET, salt, 100000, 32, 'sha256');

  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  const tag = cipher.getAuthTag();

  // Return the complete payload string
  return `v1:${iv.toString('hex')}:${salt.toString('hex')}:${tag.toString('hex')}:${encrypted}`;
}

/**
 * Decrypts a ciphertext generated by the encrypt function.
 */
export function decrypt(ciphertext: string): string {
  if (!ciphertext) return ciphertext;
  
  let ivHex: string, saltHex: string, tagHex: string, encryptedHex: string;
  const parts = ciphertext.split(':');
  
  if (parts.length === 5 && parts[0] === 'v1') {
    // New versioned format
    ivHex = parts[1] as string;
    saltHex = parts[2] as string;
    tagHex = parts[3] as string;
    encryptedHex = parts[4] as string;
  } else if (parts.length === 4) {
    // Legacy unversioned format
    ivHex = parts[0] as string;
    saltHex = parts[1] as string;
    tagHex = parts[2] as string;
    encryptedHex = parts[3] as string;
  } else {
    throw new Error('Invalid encrypted text format');
  }
  
  const iv = Buffer.from(ivHex, 'hex');
  const salt = Buffer.from(saltHex, 'hex');
  const tag = Buffer.from(tagHex, 'hex');
  
  // Derive the exact same key using the extracted salt
  const key = crypto.pbkdf2Sync(env.API_SECRET, salt, 100000, 32, 'sha256');

  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(tag);
  
  let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  
  return decrypted;
}
